### ISSUE TITLE
Code needs a license

### ISSUE THREAD

**Issue by 3vivekb** [ManhanGroup/Alpaca#1]
This code needs a license.

MIT is preferred.

**Comment by 3vivekb** [comment]
Actually, there is a license in the code.  There should probably be one in the main repo folder though.

https://github.com/ManhanGroup/Alpaca/blob/master/muLand/src/license_lgpl.txt

**Comment by ColbyBrown** [comment]
Hi Vivek, I had actually tried to fix this 16 days ago, but apparently it somehow got stuck due to a GitHub glitch.

Thanks,

Colby M Brown AICP PTP
Voice: +1 (413) 282-8629
